name: lista_de_contatos_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  brasil_fields: ^1.14.0
  dio: ^5.3.3
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  image_cropper: ^5.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/images/user.png
  uses-material-design: true
